# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes
ENABLE_LINTERS:
  - PYTHON_BLACK
  - PYTHON_ISORT
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: true
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
PRINT_ALPACA: false
TEXT_REPORTER: false
SHOW_SKIPPED_LINTERS: false
LINTER_RULES_PATH: .
#FILTER_REGEX_INCLUDE: (src/)
FILTER_REGEX_EXCLUDE: (tests/)
PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_ISORT_CONFIG_FILE: pyproject.toml
SQL_SQLFLUFF_RULES_PATH: .
